name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven 3.9.2
      run: |
        # Remove any existing Maven installations
        sudo rm -rf /usr/local/maven
        
        # Download and install Maven 3.9.2
        wget https://archive.apache.org/dist/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz
        tar -xzf apache-maven-3.9.2-bin.tar.gz
        sudo mv apache-maven-3.9.2 /usr/local/maven

        # Update environment variables
        echo "M2_HOME=/usr/local/maven" | sudo tee -a /etc/environment
        echo "PATH=\$PATH:/usr/local/maven/bin" | sudo tee -a /etc/environment
        source /etc/environment
        
        # Verify Maven version
        mvn -version

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
